Fixture files can be loaded from your project's 'fixtures' directory. So
[,groovy]
----
fixtureLoader.load("gina")
----

will load fixtures from the file 'fixtures/gina.groovy'.

You can load multiple fixtures at once by passing more than one fixture file name...

[,groovy]
----
fixtureLoader.load("gina", "otherfixture")
----

Beans in different fixture files can reference each other. As long as the necessary fixtures are loaded, the references will resolve.

==== Loading via patterns

Ant style path patterns are supported...

[,groovy]
----
fixtureLoader.load("books/*")
----

This would load all the *.groovy files in the 'fixtures/books' directory.

==== Logging

An implicit logger is available in all fixture files. It's name is `grails.app.fixture.inline.«file path»`, where «file path» is that path relative from the fixtures directory.

==== Changing the fixtures directory

To change the path to your fixtures directory, e.g. to share fixtures between different projects, change `grails.plugin.fixtures.directory`:

[,groovy]
----
grails.plugin.fixtures.directory = "path/to/fixtures" // defaults to "fixtures"
---